### ISSUE TITLE
The Image transformation is still missing the support of private secret

### ISSUE THREAD

**Issue by houshengbo** [knative/serving-operator#221]
@garron As we discussed on slack, we probably need to verify if this support is missing for image transformation. If so, we will add it the same way as we did for the deployment transformation.

**Comment by garron** [comment]
For context, this is related to #124

**Comment by garron** [comment]
I've taken a look at adding this and it's pretty straightforward. However, it's worth pointing out that this will not result in the queue proxy in the various namespaces that ksvcs are deployed to using the imagePullSecrets.

As far as I can tell, there might not be a practical way to get the queue proxy using imagePullSecrets without changes to serving. Because the queue proxy runs in various namespaces, any imagePullSecrets would have to exist in those namespaces or be copied there.

**Comment by garron** [comment]
CC: @mattmoor

**Comment by garron** [comment]
I wrote up https://github.com/knative/serving/issues/6075 to track next steps around getting imagePullSecrets working with the queue proxy.
