### ISSUE TITLE
When will this support 13.2?

### ISSUE THREAD

**Issue by AceHack** [knative/serving-operator#378]
What the average lag time from release?

**Comment by Cynocracy** [comment]
There's currently a proposal to have this release unbundled from the operand.

https://docs.google.com/document/d/1ehd5Yx4aSottuv7FYW4JeplNULJCs7nnDfy29y3NH8k/edit

I think that's the best way to avoid needing to keep up with the Operand 1:1 with releases.
Today I don't know if we have any process in place other than manual releases. I'll ask around.

**Comment by houshengbo** [comment]
@AceHack Based on the historic record, we usually need one or two weeks after serving or eventing officially cuts a minor release, since we need to verify all the tests for latest manifest.

For to catch up the patch release, operator usually needs one week, because the auto-release cuts patch release every Tue.

**Comment by houshengbo** [comment]
https://github.com/knative/serving-operator/releases/tag/v0.13.2
The artifacts were released this Monday.
