### ISSUE TITLE
Failed to recreate the deployment of knative serving, after applying PR #83

### ISSUE THREAD

**Issue by houshengbo** [knative/serving-operator#92]
As we are undergoing the transition to use pkg/controller, the PR https://github.com/knative/serving-operator/pull/83 now brings into a failure to recreation the knative serving deployment.

After the operator installs the knative serving, we should be able to see 6 deployments available, like autoscaler, activator, etc. When we remove any of them, for example activator, by the command "`kubectl delete deployment activator -n knative-serving`", a new activator will be recreated, but the PR #83 cannot revive the deployment.

We need to re-implement the following function at https://github.com/knative/serving-operator/blob/master/pkg/reconciler/knativeserving/knativeserving_controller.go#L237 for the PR #83, in order to enable the deployment recreation.

**Comment by yu2003w** [comment]
I tried to fix similar problem several days ago in PR. https://github.com/knative/serving-operator/pull/89

Could we make install stage executed again rather than create the resource directly at line 21~23? https://github.com/houshengbo/serving-operator/blob/refactor-reconciler/pkg/reconciler/knativeserving/knativeserving.go#L221

Before ```return err``` in checkDeployments, status should be set to make install stage executed again.

**Comment by houshengbo** [comment]
This one is not valid any more, since the new PR resolves everything: https://github.com/knative/serving-operator/pull/146
